### ISSUE TITLE
Frequent server-side errors causing issues on browser app (fail_fetch_status)

### ISSUE THREAD

**Issue by taylankasap** [raindropio/app#115] opened 2024-01-07 11:41 UTC
By "frequent" I mean something around 1 in 15 requests.

Steps to reproduce:
1. Go to this URL https://api.raindrop.io/v1/raindrop/1234567890
2. Keep refreshing the page

Expected result: I should keep seeing the 404 error.

Actual result: Sometimes I see the "Internal Server Error" (500).

Note: This issue is not specific to this endpoint.

---

Examples from the end-user's point of view:

Save bookmark (I've changed the ID in the URL assuming it's my account or collection ID):
![image](https://github.com/raindropio/app/assets/4192479/426c8f46-78d5-4f13-9f8f-bed2ac9a0862)

Upload image by drag & drop to sidebar:
![image](https://github.com/raindropio/app/assets/4192479/89df1fae-850c-4781-8b69-803982c6e6b7)

I know this GitHub repo is for the app and not the back-end but back-end errors are inevitable. So the app also should handle errors better. Maybe a retry mechanism or _at least_ a retry button. If this is something you agree with I can try to contribute.

**Comment by exentrich** [comment] 2024-01-08 12:53
Sorry for inconvenience. The issue is fixed now, please let me know if this happen again

**Closed by exentrich** 2024-01-08 12:53 UTC
