### ISSUE TITLE
Firefox extension creating duplicate folders

### ISSUE THREAD

**Issue by PapaPeskwo** [raindropio/app#128] opened 2024-04-12 16:05 UTC
The extension keeps creating duplicate folders. It happens when you press the extension>collection>create a new nested collection. Below is an image showing my statement. It happens all the time and I've just noticed it everywhere in my bookmarkstree

![image](https://github.com/raindropio/app/assets/58036451/1c855daf-b01c-49ba-adac-619581648bc9)

**Comment by edk** [comment] 2024-04-16 17:25
I noticed the same problem with the web site in firefox (so not just the extension)
When I create a collection, it creates two, including when I create a nested collection.

Strangely enough, I don't notice that behavior in chrome.  Again, not the extension, but the website 🤷 

Apologies if this isn't the right place for this bug report (anyone know of a better place to report or discuss this)?

**Comment by PapaPeskwo** [comment] 2024-04-17 07:31
Yes, I also noticed it with the website doing the same thing... I'm using Firefox and haven't tried the chrome version.

**Comment by exentrich** [comment] 2024-04-17 14:29
Sorry! The issue is fixed in version 6.6.22. Will be available in next few hours

**Closed by exentrich** 2024-04-17 14:29 UTC
